language: node_js

# Use trusty
sudo: true
dist: trusty

# Don't build commits in the queue if a new commit arrives
git:
  depth: 1

# node versions to test
node_js:
  - "4"    # minimum version
  - "5"    # latest LTS version
  - "6"    # latest version

# If any version fails, cancel the others
matrix:
  fast_finish: true

before_script:
  - npm install -g gulp-cli

script: gulp
